// demo/demo-front/demo-next/src/app/components/board/WriteButton.tsx
"use client";

import { useRouter } from "next/navigation";

const WriteButton = () => {
  const router = useRouter();

  const handleClick = () => {
    router.push("/board/new");
  };

  return (
    <div className="flex justify-end">
      <button
        onClick={handleClick}
        className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700"
      >
        글쓰기
      </button>
    </div>
  );
};

export default WriteButton;

// demo/demo-front/demo-vue/src/components/board/WriteButton.vue
<template>
  <div class="flex justify-end">
    <router-link
      to="/board/new"
      class="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700"
    >
      글쓰기
    </router-link>
  </div>
</template>

<script setup>
// No script logic needed if using router-link directly for navigation.
// If programmatic navigation or other logic were needed, useRouter could be used here.
</script>

<style scoped>
/* Component-specific styles if needed */
</style>
